spring:
    messages:
    # 国际化资源文件路径
        basename: static/jq
    application:
        name: road-gis
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: road_gis
        #url: jdbc:postgresql://32.32.21.200:5432/qinhuai?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
        #username: postgres
        #password: 123456
        url: jdbc:postgresql://localhost:5432/qinhuai?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
        username: postgres
        password: 1234567890
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        druid:
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select version()
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          web-stat:
            enabled: true
            url-patterns: "/*"
            exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
          stat-view-servlet:
            enabled: true
            login-username: admin
            login-password: 123456
            allow: 127.0.0.1,192.168.163.1
            deny: 192.168.0.73
      # 模板引擎
    thymeleaf:
        mode: HTML5
        encoding: utf-8
        prefix: classpath:/templates/
        check-template-location: false
        suffix: .html
        servlet:
          content-type: text/html
            # 禁用缓存
        cache: false
    resources:
        chain:
          strategy:
             content:
                enabled: true
                paths: /**
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

mybatis:
    basepackage: com.ihooyah.roadgis.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"


server:
    port: 9009
    servlet:
      context-path: /api
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30




# 日志配置
#logging:
  #level:
    #com.ihooyah.roadgis: debug